In [1]:
import numpy as np
arr_a = np.arange(1, 10)  # 1,2,...,9
arr_b = np.arange(1, 10).reshape(3, 3)
print("arr_a:", arr_a)
print("arr_a shape:", arr_a.shape)
print("arr_a dtype:", arr_a.dtype)
print()
print("arr_b:\n", arr_b)
print("arr_b shape:", arr_b.shape)
print("arr_b dtype:", arr_b.dtype)


arr_a: [1 2 3 4 5 6 7 8 9]
arr_a shape: (9,)
arr_a dtype: int64

arr_b:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr_b shape: (3, 3)
arr_b dtype: int64
